spring:
  config:
    activate:
      on-profile: local
  jpa:
    show-sql: false

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true

tillora:
  security:
    cookie:
      secure: false
